
SELECT *
FROM ACTEUR,JOUER,FILM,GENRE
WHERE (IDA=IDACTEUR AND IDFILM=IDF AND IDG=IDGENRE) AND
 (DESCRIPTION='COMEDIE' OR DESCRIPTION='POILICIER');

SELECT *
FROM REALISATEUR,FILM
WHERE IDR=IDREALISATEUR AND NOM='DAROUSSIN' AND ANNÉE=2000;

SELECT IDACTEUR , IDREALISATEUR
FROM REALISATEUR,FILM,JOUER
WHERE IDFILM=IDF AND IDREALISATEUR=IDR
ORDER BY IDREALISATEUR , IDACTEUR;


SELECT DESCRIPTION
FROM JOUER,ACTEUR,GENRE,FILM
WHERE IDA=IDACTEUR AND IDF=IDFILM AND IDG=IDGENRE AND NOM='AL' AND PRENOM='PRENOM';

SELECT IDREALISATEUR
FROM FILM,GENRE
WHERE IDG=IDGENRE AND DESCRIPTION='COMEDIEMUSICALE'
ORDER BY ANNEE;


SELECT COUNT(*) AS NOMBREFILM
FROM FILM ;

SELECT MIN(ANNEE)
FROM FILM;

SELECT MAX(SALAIRE) AS MAXIMUM,MIN(SALAIRE) AS MINIMUM,AVG(SALAIRE) AS MOYENNE
FROM JOUER;

SELECT MAX(NBSPECTATEURS) AS MAXIMUM,MIN((NBSPECTATEURS) AS MINIMUM,AVG((NBSPECTATEURS) AS MOYENNE
FROM FILM,GENRE
WHERE IDG=IDGENRE AND DESCRIPTION='COMIQUE';

SELECT AVG(SALAIRE)/AVG(NBSPECTATEURS) AS RATIO
FROM ACTEUR,JOUER,FILM
WHERE IDA=IDACTEUR AND IDFILM=IDF ;


 
