DROP TABLE OPERATEUR;
DROP TABLE MACHINE; 
DROP TABLE PIECE;
DROP TABLE QUALIFIE_SUR;


CREATE TABLE OPERATEUR(
NUMERO VARCHAR (20)PRIMARY KEY,
NOM   CHARACTER(20) NOT NULL,
AGE   NUMERIC(2) );

CREATE TABLE MACHINE(
REFERENCE_M VARCHAR(20) PRIMARY KEY,
DESIGNATION_M CHARACTER(20) NOT NULL);

CREATE TABLE PIECE(
REFERENCE_P VARCHAR(20) PRIMARY KEY,
DESIGNATION_P CHARACTER(20) NOT NULL,
REFERENCE_MACHINE VARCHAR(20),
NUMERO_OPERATEUR VARCHAR(20),
QUANTITE NUMERIC(5),
CONSTRAINT P_M FOREIGN KEY (REFERENCE_MACHINE) REFERENCES MACHINE (REFERENCE_M),
CONSTRAINT P_O FOREIGN KEY (NUMERO_OPERATEUR) REFERENCES OPERATEUR (NUMERO)
);

CREATE TABLE QUALIFIE_SUR(
NUMERO_OP VARCHAR (20), 
REFERENCE_MACH VARCHAR(20), 
DT  DATE NOT NULL,
FOREIGN KEY (NUMERO_OP) REFERENCES OPERATEUR (NUMERO),
FOREIGN KEY (REFERENCE_MACH) REFERENCES MACHINE(REFERENCE_M),
PRIMARY KEY(NUMERO_OP,REFERENCE_MACH));
