/* CREATION ET MODIFICATION D'ATTRIBUTS */
ALTER TABLE ABONNE
ADD DATE_NAI DATE;

ALTER TABLE ABONNE
ADD TYPE_AB VARCHAR(30) CHECK (TYPE_AB IN('ADULTE','ENFANT')) ENABLE;

ALTER TABLE ABONNE
ADD CAT_AB VARCHAR(30) CHECK (CAT_AB IN ('REGULIER','OCCASIONNEL','APROBLEME','EXCLU')) ENABLE;


INSERT INTO ABONNE VALUES (900541,'HOOD','JAMES','SETE',32,100,NULL,'31-JAN-1985','ADULTE','REGULIER');

INSERT INTO ABONNE VALUES (900541,'CARRIE','OPWELL','MARSEILLE',32,100,NULL,'03-JAN-1985','ADULTE','REGULIER');


ALTER TABLE ABONNE
MODIFY TARIF NUMBER(5);


UPDATE  ABONNE
SET  TARIF=1000
WHERE NOM='HOOD';


ALTER TABLE MOT_CLEF
ADD MOT_PERE VARCHAR(30);

ALTER TABLE MOT_CLEF
ADD CONSTRAINT FK_MOT_PERE FOREIGN KEY (MOT_PERE) REFERENCES MOT_CLEF(ID); 

/* CREATION DE RELATIONS */
CREATE TABLE AUTEUR (
       ID_AUTEUR INT NOT NULL,
       NOM VARCHAR(20) ,
       PRENOM VARCHAR(20),
       NATIONALITE VARCHAR(20),
       PRIMARY KEY(ID_AUTEUR)
);

CREATE TABLE ECRIT (
       ID_AUTEUR INT NOT NULL,
       ISBN VARCHAR(20) NOT NULL,
       CONSTRAINT FK_AUTEUR FOREIGN KEY (ID_AUTEUR) REFERENCES AUTEUR(ID_AUTEUR),
       CONSTRAINT FK_LIVRE FOREIGN KEY (ISBN) REFERENCES LIVRE(ISBN),
       PRIMARY KEY(ID_AUTEUR,ISBN)
);



ABONNE	(NUM_AB,NOM,PRENOM,VILLE,AGE,TARIF,REDUC)	
EXEMPLAIRE(NUMERO,DATE_ACHAT,PRIX,CODE_PRET,ETAT,ISBN)	
LIVRE(ISBN,TITRE,SIECLE,CATEGORIE)	
MOT_CLEF(MOT,MOT_PERE)	
EMPRUNT	(NUM_AB,NUM_EX,	D_EMPRUNT,D_RETOUR,D_RET_REEL,NB_RELANCE)	
CARACTERISE(ISBN,MOT)
AUTEUR(NOM,PRENOM,NATIONALITE)
ECRIT(ISBN,NOMN,PRENOM)

/* MISE À JOUR DES DONNÉES */
UPDATE ABONNE
SET TYPE_AB = 'ADULTE' WHERE AGE > 16
;

UPDATE ABONNE
SET TYPE_AB = 'ENFANT' WHERE AGE < 16
;


UPDATE ABONNE
SET TYPE_AB = NULL  WHERE AGE = NULL
;


/* TABLES SYSTEMES  */
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='AUTEUR';

SELECT TABLE_NAME AS BD_BIBLIO FROM USER_TABLES
WHERE TABLE_NAME='ABONNE'
      OR
      TABLE_NAME='AUTEUR'
      OR
      TABLE_NAME='LIVRE'
      OR
      TABLE_NAME='EXEMPLAIRE'
      OR
      TABLE_NAME='MOT_CLEF'
      OR
      TABLE_NAME='ECRIT'
      OR
      TABLE_NAME='EMPRUNT'
      OR
      TABLE_NAME='CARACTERISE'
;

SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='ABONNE';

DESC USER_TAB_COLUMNS ;

SELECT COLUMN_NAME ,DATA_TYPE,TABLE_NAME FROM USER_TAB_COLUMNS;

SELECT COUNT (COLUMN_NAME)
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='ABONNE'
      OR
      TABLE_NAME='AUTEUR'
      OR
      TABLE_NAME='LIVRE'
      OR
      TABLE_NAME='EXEMPLAIRE'
      OR
      TABLE_NAME='MOT_CLEF'
      OR
      TABLE_NAME='ECRIT'
      OR
      TABLE_NAME='EMPRUNT'
      OR
      TABLE_NAME='CARACTERISE'
;


/* question 11 */
