CREATE OR REPLACE FUNCTION F1 (COEFF IN FLOAT,NUM_A IN INTEGER)
RETURN FLOAT IS
REDUC_A FLOAT;
BEGIN
SELECT REDUC INTO REDUC_A FROM ABONNE WHERE NUM_AB=NUM_A;
REDUC_A := REDUC_A * COEFF;
RETURN REDUC_A;
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

/* select F1(6.5,901001)  from DUAL ; APPEL DE LA FONCTION DANS LA TABLE DUAL*/ 
